{-
   ElevenLabs API Documentation

   This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://beta.elevenlabs.io. Our API is experimental so all endpoints are subject to change.

   OpenAPI Version: 3.0.2
   ElevenLabs API Documentation API version: 1.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : ElevenLabsAPIDocumentation.API.History
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module ElevenLabsAPIDocumentation.API.History where

import ElevenLabsAPIDocumentation.Core
import ElevenLabsAPIDocumentation.MimeTypes
import ElevenLabsAPIDocumentation.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** History

-- *** deleteHistoryItemV1HistoryHistoryItemIdDelete

-- | @DELETE \/v1\/history\/{history_item_id}@
-- 
-- Delete History Item
-- 
-- Delete a history item by its ID
-- 
deleteHistoryItemV1HistoryHistoryItemIdDelete
  :: HistoryItemId -- ^ "historyItemId" -  History item ID to be used, you can use GET https://api.elevenlabs.io/v1/history to receive a list of history items and their IDs.
  -> ElevenLabsAPIDocumentationRequest DeleteHistoryItemV1HistoryHistoryItemIdDelete MimeNoContent AnyType MimeJSON
deleteHistoryItemV1HistoryHistoryItemIdDelete (HistoryItemId historyItemId) =
  _mkRequest "DELETE" ["/v1/history/",toPath historyItemId]

data DeleteHistoryItemV1HistoryHistoryItemIdDelete  

-- | /Optional Param/ "xi-api-key" - Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
instance HasOptionalParam DeleteHistoryItemV1HistoryHistoryItemIdDelete XiApiKey where
  applyOptionalParam req (XiApiKey xs) =
    req `addHeader` toHeader ("xi-api-key", xs)
-- | @application/json@
instance Produces DeleteHistoryItemV1HistoryHistoryItemIdDelete MimeJSON


-- *** downloadHistoryItemsV1HistoryDownloadPost

-- | @POST \/v1\/history\/download@
-- 
-- Download History Items
-- 
-- Download one or more history items. If one history item ID is provided, we will return a single audio file. If more than one history item IDs are provided, we will provide the history items packed into a .zip file.
-- 
downloadHistoryItemsV1HistoryDownloadPost
  :: (Consumes DownloadHistoryItemsV1HistoryDownloadPost MimeJSON, MimeRender MimeJSON BodyDownloadHistoryItemsV1HistoryDownloadPost)
  => BodyDownloadHistoryItemsV1HistoryDownloadPost -- ^ "bodyDownloadHistoryItemsV1HistoryDownloadPost"
  -> ElevenLabsAPIDocumentationRequest DownloadHistoryItemsV1HistoryDownloadPost MimeJSON NoContent MimeNoContent
downloadHistoryItemsV1HistoryDownloadPost bodyDownloadHistoryItemsV1HistoryDownloadPost =
  _mkRequest "POST" ["/v1/history/download"]
    `setBodyParam` bodyDownloadHistoryItemsV1HistoryDownloadPost

data DownloadHistoryItemsV1HistoryDownloadPost 
instance HasBodyParam DownloadHistoryItemsV1HistoryDownloadPost BodyDownloadHistoryItemsV1HistoryDownloadPost 

-- | /Optional Param/ "xi-api-key" - Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
instance HasOptionalParam DownloadHistoryItemsV1HistoryDownloadPost XiApiKey where
  applyOptionalParam req (XiApiKey xs) =
    req `addHeader` toHeader ("xi-api-key", xs)

-- | @application/json@
instance Consumes DownloadHistoryItemsV1HistoryDownloadPost MimeJSON

instance Produces DownloadHistoryItemsV1HistoryDownloadPost MimeNoContent


-- *** getAudioFromHistoryItemV1HistoryHistoryItemIdAudioGet

-- | @GET \/v1\/history\/{history_item_id}\/audio@
-- 
-- Get Audio From History Item
-- 
-- Returns the audio of an history item.
-- 
getAudioFromHistoryItemV1HistoryHistoryItemIdAudioGet
  :: HistoryItemId -- ^ "historyItemId" -  History item ID to be used, you can use GET https://api.elevenlabs.io/v1/history to receive a list of history items and their IDs.
  -> ElevenLabsAPIDocumentationRequest GetAudioFromHistoryItemV1HistoryHistoryItemIdAudioGet MimeNoContent NoContent MimeNoContent
getAudioFromHistoryItemV1HistoryHistoryItemIdAudioGet (HistoryItemId historyItemId) =
  _mkRequest "GET" ["/v1/history/",toPath historyItemId,"/audio"]

data GetAudioFromHistoryItemV1HistoryHistoryItemIdAudioGet  

-- | /Optional Param/ "xi-api-key" - Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
instance HasOptionalParam GetAudioFromHistoryItemV1HistoryHistoryItemIdAudioGet XiApiKey where
  applyOptionalParam req (XiApiKey xs) =
    req `addHeader` toHeader ("xi-api-key", xs)
instance Produces GetAudioFromHistoryItemV1HistoryHistoryItemIdAudioGet MimeNoContent


-- *** getGeneratedItemsV1HistoryGet

-- | @GET \/v1\/history@
-- 
-- Get Generated Items
-- 
-- Returns metadata about all your generated audio.
-- 
getGeneratedItemsV1HistoryGet
  :: ElevenLabsAPIDocumentationRequest GetGeneratedItemsV1HistoryGet MimeNoContent GetHistoryResponseModel MimeJSON
getGeneratedItemsV1HistoryGet =
  _mkRequest "GET" ["/v1/history"]

data GetGeneratedItemsV1HistoryGet  

-- | /Optional Param/ "page_size" - How many history items to return at maximum. Can not exceed 1000, defaults to 100.
instance HasOptionalParam GetGeneratedItemsV1HistoryGet PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)

-- | /Optional Param/ "start_after_history_item_id" - After which history_item_id to start fetching, use this parameter to paginate across a large collection of history items. In case this parameter is not provided history items will be fetched starting from the most recently created one ordered descending by their creation date.
instance HasOptionalParam GetGeneratedItemsV1HistoryGet StartAfterHistoryItemId where
  applyOptionalParam req (StartAfterHistoryItemId xs) =
    req `addQuery` toQuery ("start_after_history_item_id", Just xs)

-- | /Optional Param/ "xi-api-key" - Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
instance HasOptionalParam GetGeneratedItemsV1HistoryGet XiApiKey where
  applyOptionalParam req (XiApiKey xs) =
    req `addHeader` toHeader ("xi-api-key", xs)
-- | @application/json@
instance Produces GetGeneratedItemsV1HistoryGet MimeJSON


-- *** getHistoryItemByIDV1HistoryHistoryItemIdGet

-- | @GET \/v1\/history\/{history_item_id}@
-- 
-- Get History Item By Id
-- 
-- Returns information about an history item by its ID.
-- 
getHistoryItemByIDV1HistoryHistoryItemIdGet
  :: HistoryItemId -- ^ "historyItemId" -  History item ID to be used, you can use GET https://api.elevenlabs.io/v1/history to receive a list of history items and their IDs.
  -> ElevenLabsAPIDocumentationRequest GetHistoryItemByIDV1HistoryHistoryItemIdGet MimeNoContent HistoryItemResponseModel MimeJSON
getHistoryItemByIDV1HistoryHistoryItemIdGet (HistoryItemId historyItemId) =
  _mkRequest "GET" ["/v1/history/",toPath historyItemId]

data GetHistoryItemByIDV1HistoryHistoryItemIdGet  

-- | /Optional Param/ "xi-api-key" - Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
instance HasOptionalParam GetHistoryItemByIDV1HistoryHistoryItemIdGet XiApiKey where
  applyOptionalParam req (XiApiKey xs) =
    req `addHeader` toHeader ("xi-api-key", xs)
-- | @application/json@
instance Produces GetHistoryItemByIDV1HistoryHistoryItemIdGet MimeJSON

