{-
   ElevenLabs API Documentation

   This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://beta.elevenlabs.io. Our API is experimental so all endpoints are subject to change.

   OpenAPI Version: 3.0.2
   ElevenLabs API Documentation API version: 1.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : ElevenLabsAPIDocumentation.API.Voices
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module ElevenLabsAPIDocumentation.API.Voices where

import ElevenLabsAPIDocumentation.Core
import ElevenLabsAPIDocumentation.MimeTypes
import ElevenLabsAPIDocumentation.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Voices

-- *** addVoiceV1VoicesAddPost

-- | @POST \/v1\/voices\/add@
-- 
-- Add Voice
-- 
-- Add a new voice to your collection of voices in VoiceLab.
-- 
addVoiceV1VoicesAddPost
  :: (Consumes AddVoiceV1VoicesAddPost MimeMultipartFormData)
  => Name -- ^ "name" -  The name that identifies this voice. This will be displayed in the dropdown of the website.
  -> Files -- ^ "files" -  One or more audio files to clone the voice from
  -> ElevenLabsAPIDocumentationRequest AddVoiceV1VoicesAddPost MimeMultipartFormData AddVoiceResponseModel MimeJSON
addVoiceV1VoicesAddPost (Name name) (Files files) =
  _mkRequest "POST" ["/v1/voices/add"]
    `_addMultiFormPart` NH.partLBS "name" (mimeRender' MimeMultipartFormData name)
    `_addMultiFormPart` NH.partFileSource "files" files

data AddVoiceV1VoicesAddPost  

-- | /Optional Param/ "description" - How would you describe the voice?
instance HasOptionalParam AddVoiceV1VoicesAddPost Description where
  applyOptionalParam req (Description xs) =
    req `_addMultiFormPart` NH.partLBS "description" (mimeRender' MimeMultipartFormData xs)

-- | /Optional Param/ "labels" - Serialized labels dictionary for the voice.
instance HasOptionalParam AddVoiceV1VoicesAddPost Labels where
  applyOptionalParam req (Labels xs) =
    req `_addMultiFormPart` NH.partLBS "labels" (mimeRender' MimeMultipartFormData xs)

-- | /Optional Param/ "xi-api-key" - Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
instance HasOptionalParam AddVoiceV1VoicesAddPost XiApiKey where
  applyOptionalParam req (XiApiKey xs) =
    req `addHeader` toHeader ("xi-api-key", xs)

-- | @multipart/form-data@
instance Consumes AddVoiceV1VoicesAddPost MimeMultipartFormData

-- | @application/json@
instance Produces AddVoiceV1VoicesAddPost MimeJSON


-- *** deleteVoiceV1VoicesVoiceIdDelete

-- | @DELETE \/v1\/voices\/{voice_id}@
-- 
-- Delete Voice
-- 
-- Deletes a voice by its ID.
-- 
deleteVoiceV1VoicesVoiceIdDelete
  :: VoiceId -- ^ "voiceId" -  Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices.
  -> ElevenLabsAPIDocumentationRequest DeleteVoiceV1VoicesVoiceIdDelete MimeNoContent AnyType MimeJSON
deleteVoiceV1VoicesVoiceIdDelete (VoiceId voiceId) =
  _mkRequest "DELETE" ["/v1/voices/",toPath voiceId]

data DeleteVoiceV1VoicesVoiceIdDelete  

-- | /Optional Param/ "xi-api-key" - Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
instance HasOptionalParam DeleteVoiceV1VoicesVoiceIdDelete XiApiKey where
  applyOptionalParam req (XiApiKey xs) =
    req `addHeader` toHeader ("xi-api-key", xs)
-- | @application/json@
instance Produces DeleteVoiceV1VoicesVoiceIdDelete MimeJSON


-- *** editVoiceSettingsV1VoicesVoiceIdSettingsEditPost

-- | @POST \/v1\/voices\/{voice_id}\/settings\/edit@
-- 
-- Edit Voice Settings
-- 
-- Edit your settings for a specific voice. \"similarity_boost\" corresponds to\"Clarity + Similarity Enhancement\" in the web app and \"stability\" corresponds to \"Stability\" slider in the web app.
-- 
editVoiceSettingsV1VoicesVoiceIdSettingsEditPost
  :: (Consumes EditVoiceSettingsV1VoicesVoiceIdSettingsEditPost MimeJSON, MimeRender MimeJSON Settings)
  => Settings -- ^ "settings"
  -> VoiceId -- ^ "voiceId" -  Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices.
  -> ElevenLabsAPIDocumentationRequest EditVoiceSettingsV1VoicesVoiceIdSettingsEditPost MimeJSON AnyType MimeJSON
editVoiceSettingsV1VoicesVoiceIdSettingsEditPost settings (VoiceId voiceId) =
  _mkRequest "POST" ["/v1/voices/",toPath voiceId,"/settings/edit"]
    `setBodyParam` settings

data EditVoiceSettingsV1VoicesVoiceIdSettingsEditPost 
instance HasBodyParam EditVoiceSettingsV1VoicesVoiceIdSettingsEditPost Settings 

-- | /Optional Param/ "xi-api-key" - Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
instance HasOptionalParam EditVoiceSettingsV1VoicesVoiceIdSettingsEditPost XiApiKey where
  applyOptionalParam req (XiApiKey xs) =
    req `addHeader` toHeader ("xi-api-key", xs)

-- | @application/json@
instance Consumes EditVoiceSettingsV1VoicesVoiceIdSettingsEditPost MimeJSON

-- | @application/json@
instance Produces EditVoiceSettingsV1VoicesVoiceIdSettingsEditPost MimeJSON


-- *** editVoiceV1VoicesVoiceIdEditPost

-- | @POST \/v1\/voices\/{voice_id}\/edit@
-- 
-- Edit Voice
-- 
-- Edit a voice created by you.
-- 
editVoiceV1VoicesVoiceIdEditPost
  :: (Consumes EditVoiceV1VoicesVoiceIdEditPost MimeMultipartFormData)
  => Name -- ^ "name" -  The name that identifies this voice. This will be displayed in the dropdown of the website.
  -> VoiceId -- ^ "voiceId" -  Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices.
  -> ElevenLabsAPIDocumentationRequest EditVoiceV1VoicesVoiceIdEditPost MimeMultipartFormData AnyType MimeJSON
editVoiceV1VoicesVoiceIdEditPost (Name name) (VoiceId voiceId) =
  _mkRequest "POST" ["/v1/voices/",toPath voiceId,"/edit"]
    `_addMultiFormPart` NH.partLBS "name" (mimeRender' MimeMultipartFormData name)

data EditVoiceV1VoicesVoiceIdEditPost  

-- | /Optional Param/ "files" - Audio files to add to the voice
instance HasOptionalParam EditVoiceV1VoicesVoiceIdEditPost Files where
  applyOptionalParam req (Files xs) =
    req `_addMultiFormPart` NH.partFileSource "files" xs

-- | /Optional Param/ "description" - How would you describe the voice?
instance HasOptionalParam EditVoiceV1VoicesVoiceIdEditPost Description where
  applyOptionalParam req (Description xs) =
    req `_addMultiFormPart` NH.partLBS "description" (mimeRender' MimeMultipartFormData xs)

-- | /Optional Param/ "labels" - Serialized labels dictionary for the voice.
instance HasOptionalParam EditVoiceV1VoicesVoiceIdEditPost Labels where
  applyOptionalParam req (Labels xs) =
    req `_addMultiFormPart` NH.partLBS "labels" (mimeRender' MimeMultipartFormData xs)

-- | /Optional Param/ "xi-api-key" - Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
instance HasOptionalParam EditVoiceV1VoicesVoiceIdEditPost XiApiKey where
  applyOptionalParam req (XiApiKey xs) =
    req `addHeader` toHeader ("xi-api-key", xs)

-- | @multipart/form-data@
instance Consumes EditVoiceV1VoicesVoiceIdEditPost MimeMultipartFormData

-- | @application/json@
instance Produces EditVoiceV1VoicesVoiceIdEditPost MimeJSON


-- *** getDefaultVoiceSettingsV1VoicesSettingsDefaultGet

-- | @GET \/v1\/voices\/settings\/default@
-- 
-- Get Default Voice Settings.
-- 
-- Gets the default settings for voices. \"similarity_boost\" corresponds to\"Clarity + Similarity Enhancement\" in the web app and \"stability\" corresponds to \"Stability\" slider in the web app.
-- 
getDefaultVoiceSettingsV1VoicesSettingsDefaultGet
  :: ElevenLabsAPIDocumentationRequest GetDefaultVoiceSettingsV1VoicesSettingsDefaultGet MimeNoContent VoiceSettingsResponseModel MimeJSON
getDefaultVoiceSettingsV1VoicesSettingsDefaultGet =
  _mkRequest "GET" ["/v1/voices/settings/default"]

data GetDefaultVoiceSettingsV1VoicesSettingsDefaultGet  
-- | @application/json@
instance Produces GetDefaultVoiceSettingsV1VoicesSettingsDefaultGet MimeJSON


-- *** getVoiceSettingsV1VoicesVoiceIdSettingsGet

-- | @GET \/v1\/voices\/{voice_id}\/settings@
-- 
-- Get Voice Settings
-- 
-- Returns the settings for a specific voice. \"similarity_boost\" corresponds to\"Clarity + Similarity Enhancement\" in the web app and \"stability\" corresponds to \"Stability\" slider in the web app.
-- 
getVoiceSettingsV1VoicesVoiceIdSettingsGet
  :: VoiceId -- ^ "voiceId" -  Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices.
  -> ElevenLabsAPIDocumentationRequest GetVoiceSettingsV1VoicesVoiceIdSettingsGet MimeNoContent VoiceSettingsResponseModel MimeJSON
getVoiceSettingsV1VoicesVoiceIdSettingsGet (VoiceId voiceId) =
  _mkRequest "GET" ["/v1/voices/",toPath voiceId,"/settings"]

data GetVoiceSettingsV1VoicesVoiceIdSettingsGet  

-- | /Optional Param/ "xi-api-key" - Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
instance HasOptionalParam GetVoiceSettingsV1VoicesVoiceIdSettingsGet XiApiKey where
  applyOptionalParam req (XiApiKey xs) =
    req `addHeader` toHeader ("xi-api-key", xs)
-- | @application/json@
instance Produces GetVoiceSettingsV1VoicesVoiceIdSettingsGet MimeJSON


-- *** getVoiceV1VoicesVoiceIdGet

-- | @GET \/v1\/voices\/{voice_id}@
-- 
-- Get Voice
-- 
-- Returns metadata about a specific voice.
-- 
getVoiceV1VoicesVoiceIdGet
  :: VoiceId -- ^ "voiceId" -  Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices.
  -> ElevenLabsAPIDocumentationRequest GetVoiceV1VoicesVoiceIdGet MimeNoContent VoiceResponseModel MimeJSON
getVoiceV1VoicesVoiceIdGet (VoiceId voiceId) =
  _mkRequest "GET" ["/v1/voices/",toPath voiceId]

data GetVoiceV1VoicesVoiceIdGet  

-- | /Optional Param/ "with_settings" - If set will return settings information corresponding to the voice, requires authorization.
instance HasOptionalParam GetVoiceV1VoicesVoiceIdGet WithSettings where
  applyOptionalParam req (WithSettings xs) =
    req `addQuery` toQuery ("with_settings", Just xs)

-- | /Optional Param/ "xi-api-key" - Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
instance HasOptionalParam GetVoiceV1VoicesVoiceIdGet XiApiKey where
  applyOptionalParam req (XiApiKey xs) =
    req `addHeader` toHeader ("xi-api-key", xs)
-- | @application/json@
instance Produces GetVoiceV1VoicesVoiceIdGet MimeJSON


-- *** getVoicesV1VoicesGet

-- | @GET \/v1\/voices@
-- 
-- Get Voices
-- 
-- Gets a list of all available voices for a user.
-- 
getVoicesV1VoicesGet
  :: ElevenLabsAPIDocumentationRequest GetVoicesV1VoicesGet MimeNoContent GetVoicesResponseModel MimeJSON
getVoicesV1VoicesGet =
  _mkRequest "GET" ["/v1/voices"]

data GetVoicesV1VoicesGet  

-- | /Optional Param/ "xi-api-key" - Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
instance HasOptionalParam GetVoicesV1VoicesGet XiApiKey where
  applyOptionalParam req (XiApiKey xs) =
    req `addHeader` toHeader ("xi-api-key", xs)
-- | @application/json@
instance Produces GetVoicesV1VoicesGet MimeJSON

